version: '3.0'
services:
  pg_reminder_bot:
    image: registry2.bale.ai:2443/balepostgres:1.6.0
    container_name: pg_reminder_bot
    restart: always
    environment:
      - POSTGRES_USER=reminder_bot
      - POSTGRES_PASSWORD=postgres123456
      - POSTGRES_DB=reminder_db
      - TZ=Asia/Tehran
    volumes:
      - /home/docker/volumes/pg_reminder_bot/postgres/:/var/lib/postgresql/data/
    ports:
      - "5500:5432"

  reminder_bot:
    image: registry2.bale.ai:2443/reminder_bot:0.0-0
    container_name: reminder_bot
    environment:
      #   PostgreSQL Config
      - POSTGRES_USER=reminder_bot
      - POSTGRES_PASSWORD=postgres123456
      - POSTGRES_DB=reminder_db
      - POSTGRES_HOST=pg_reminder_bot
      - POSTGRES_PORT=5432
      #   Config
      - BASE_URL=wss://api.bale.ai/v1/bots/
      - TOKEN=17fcfa921bae323895d2d70e6d3d998a2b3d000e
      - CHECK_INTERVAL=0.5
      - TIME_OUT_WAIT_FOR_CHECK_CHECK_CLIENT_QUEUE=60
      - TIME_OUT_FOR_BLOCK_ON_CLIENT_QUEUE=0.5
      - TIME_OUT_FOR_BLOCK_ON_CLIENT_QUEUE=5
      #   Log config
      - USE_GRAYLOG=2
      - SOURCE=reminder_bot_source
      - GRAYLOG_HOST=192.168.21.113
      - GRAYLOG_PORT=12201
      - LOG_LEVEL=20
      - LOG_FACILITY_NAME=reminder_bot_facility
      - MONITORING_HASH=cabb3f498ac5a037f669f658f1be08c3
    depends_on:
      - pg_reminder_bot
    restart: always

